run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Allow blank assignments in tests
  
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Disable field alignment checks for simplicity
  
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  lll:
    line-length: 130  # Slightly longer for better readability
  
  goimports:
    local-prefixes: mock-service
  
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - emptyStringTest  # Allow len(s) == 0 pattern
  

  
  depguard:
    rules:
      main:
        deny:
          - pkg: "errors"
            desc: "Use fmt.Errorf instead"
        allow:
          - $all
          - mock-service

linters:
  enable:
    - bodyclose
    - copyloopvar  # Replace deprecated exportloopref
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - mnd  # Replace deprecated gomnd
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  
  disable:
    - gochecknoinits
    - gochecknoglobals
    - depguard  # Disable for now to allow internal imports

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - mnd
        - goconst
        - dupl
        - errcheck  # Allow unchecked errors in tests

    
    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
    
    # Allow long lines in error messages
    - linters:
        - lll
      source: "fmt.Fprintf.*Failed to marshal log entry"
  
  # Maximum issues count per one linter. Set to 0 to disable
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text. Set to 0 to disable
  max-same-issues: 0