version: '3.8'

services:
  mock-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config:ro
    command:
      [
        "./mock-service",
        "-config",
        "/app/config/test-config.json",
        "-port",
        "8080",
      ]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
